import type { NextConfig } from 'next'

const config: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  images: {
    // All derivatives are pre-generated by scripts/build-images.mjs, so the
    // runtime optimiser is unused. This keeps the build host-agnostic.
    unoptimized: true,
  },
  /* /journal was the blog's URL until it was renamed. Kept as a permanent
     redirect so anything already pointing at it still lands. */
  async redirects() {
    return [
      { source: '/journal', destination: '/blog', permanent: true },
      { source: '/journal/:slug', destination: '/blog/:slug', permanent: true },
    ]
  },
  async headers() {
    return [
      {
        // Derivatives are content-addressed by width + format and never mutate.
        source: '/:path(img|media)/:all*',
        headers: [{ key: 'Cache-Control', value: 'public, max-age=31536000, immutable' }],
      },
      {
        source: '/:path*',
        headers: [
          { key: 'X-Content-Type-Options', value: 'nosniff' },
          { key: 'Referrer-Policy', value: 'strict-origin-when-cross-origin' },
          { key: 'X-Frame-Options', value: 'SAMEORIGIN' },
        ],
      },
    ]
  },
}

export default config
